// menu_items.dart
const List<Map<String, String>> items = [
  {
    "name": "Fried Samosas",
    "type": "Appetizer",
    "time": "15–20 mins",
    "price": "\$8.99",
    "tag": "Spicy Grilled Indian",
    "image": "assets/images/paneer.webp",
    "category": "Appetizer",
  },
  {
    "name": "Fried Chicken",
    "type": "Specials",
    "time": "15–20 mins",
    "price": "\$8.99",
    "tag": "Spicy Grilled Indian",
    "image": "assets/images/paneer.webp",
    "category": "Specials",
  },
  {
    "name": "Gourmet Vegetarian",
    "type": "Meals",
    "time": "15–20 mins",
    "price": "\$9.30",
    "tag": "Spicy Grilled Indian",
    "image": "assets/images/paneer.webp",
    "category": "Meals",
  },
  {
    "name": "Chocolate Lava Cake",
    "type": "Desserts",
    "time": "10–15 mins",
    "price": "\$6.50",
    "tag": "Warm Chocolate Delight",
    "image": "assets/images/paneer.webp",
    "category": "Desserts",
  },
  {
    "name": "Mango Smoothie",
    "type": "Beverages",
    "time": "5–10 mins",
    "price": "\$4.99",
    "tag": "Fresh & Fruity",
    "image": "assets/images/paneer.webp",
    "category": "Beverages",
  },
  {
    "name": "Paneer Tikka",
    "type": "Appetizer",
    "time": "20–25 mins",
    "price": "\$7.50",
    "tag": "Grilled Cottage Cheese",
    "image": "assets/images/paneer.webp",
    "category": "Appetizer",
  },
  {
    "name": "Butter Chicken",
    "type": "Meals",
    "time": "25–30 mins",
    "price": "\$12.99",
    "tag": "Creamy Tomato Curry",
    "image": "assets/images/paneer.webp",
    "category": "Meals",
  },
  {
    "name": "Veggie Burger",
    "type": "Specials",
    "time": "10–15 mins",
    "price": "\$6.99",
    "tag": "Healthy and Fresh",
    "image": "assets/images/paneer.webp",
    "category": "Specials",
  },
  {
    "name": "French Fries",
    "type": "Sides",
    "time": "8–12 mins",
    "price": "\$3.50",
    "tag": "Crispy & Golden",
    "image": "assets/images/paneer.webp",
    "category": "Sides",
  },
  {
    "name": "Chicken Biryani",
    "type": "Meals",
    "time": "30–35 mins",
    "price": "\$13.49",
    "tag": "Traditional Rice Dish",
    "image": "assets/images/paneer.webp",
    "category": "Meals",
  },
  {
    "name": "Masala Dosa",
    "type": "Specials",
    "time": "20–25 mins",
    "price": "\$9.99",
    "tag": "South Indian Classic",
    "image": "assets/images/paneer.webp",
    "category": "Specials",
  },
  {
    "name": "Caesar Salad",
    "type": "Appetizer",
    "time": "10–15 mins",
    "price": "\$5.99",
    "tag": "Fresh and Crispy",
    "image": "assets/images/paneer.webp",
    "category": "Appetizer",
  },
  {
    "name": "Lemon Iced Tea",
    "type": "Beverages",
    "time": "5–8 mins",
    "price": "\$3.20",
    "tag": "Refreshing Drink",
    "image": "assets/images/paneer.webp",
    "category": "Beverages",
  },
];
